### ISSUE TITLE
Found the blog post really interesting, but your container here is not working

### ISSUE THREAD

**Issue by leognmotta** [akullpp/multiple-react-nginx#1]
To improve your tutorial you could consider adding a node version on your dockerfile, I tried to run your container and I had the following error:

```error upath@1.0.4: The engine "node" is incompatible with this module. Expected version ">=4 <=9". Got "12.7.0" ```

```error Found incompatible module.```

In fact I only changed the node version on your docker file ```FROM node:9``` or also consider updating the example to work with more recent versions

**Comment by akullpp** [comment]
Versions were not fixed, therefore the incompatibilities occured. I fixed the issues and replaced yarn with npm.
